import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    defaultPage: "1",
    //登录页配置
    loginPage: {
      loginPage: [
        {
          name: "loginA",
          position: "right",
          loginText: "登录系统",
          buttonText: "登录",
          buttonColor: "#5fa5f8",
          buttonHover: "#2460cc",
          buttonTextColor: "#fff",
          rightText: "Copyright © 顾德智能 版权所有",
          logo: "",
          backg: [],
          img: "loginA.png",
          //hover是否展示
          show: false,
          description: "中规中矩模板",
          isDefault: false,
        },
        {
          name: "loginB",
          position: "right",
          loginText: "登录系统",
          buttonText: "登录",
          buttonColor: "#8fdffb",
          buttonHover: "#318AC1",
          buttonTextColor: "#fff",
          rightText: "Copyright © 顾德智能 版权所有",
          logo: "",
          backg: [],
          img: "loginB.png",
          show: false,
          description: "左右卡片模板",
          isDefault: true,
        },
        // loginC: {
        //   name: "loginC",
        //   position: "right",
        //   loginText: "登录系统",
        //   buttonText: "登录",
        //   buttonColor: "#5fa5f8",
        //   buttonHover: "#2460cc",
        //   buttonTextColor: "#fff",
        //   rightText: "Copyright © 顾德智能 版权所有",
        //   logo: "",
        //   backg: [],
        //   img: "loginC.png",
        //   show: false,
        //   description: "多图滚动模式  ",
        // },
        {
          name: "loginD",
          position: "right",
          loginText: "登录系统",
          buttonText: "登录",
          buttonColor: "#5fa5f8",
          buttonHover: "#2460cc",
          buttonTextColor: "#fff",
          rightText: "Copyright © 顾德智能 版权所有",
          logo: "",
          backg: [],
          img: "loginD.png",
          show: false,
          description: "普普通通模板",
          isDefault: false,
        },
      ],
    },
    //悬浮效果
    hover: {
      logoHover: false,
      backgHover: false,
      loginHover: false,
      buttonHover: false,
      rightHover: false,
      waitHover: false,
    },
    //门户模板
    portal: {
      portal: [
        {
          number: "1",
          name: "portalA",
          layout: [
            {
              x: 0,
              y: 0,
              w: 8,
              h: 8,
              i: "a",
              show: false,
              component: "test1",
              name: "轮播图",
            },
            {
              x: 0,
              y: 16,
              w: 2,
              h: 3,
              i: "b",
              show: false,
              component: "test2",
              name: "按钮",
            },
            {
              x: 4,
              y: 16,
              w: 2,
              h: 3,
              i: "c",
              show: false,
              component: "test3",
              name: "按钮2",
            },
            { x: 0, y: 22, w: 4, h: 4, i: "d", show: false },
            { x: 8, y: 16, w: 2, h: 3, i: "e", show: false },
            { x: 16, y: 22, w: 8, h: 4, i: "f", show: false },
            { x: 16, y: 0, w: 4, h: 3, i: "g", show: false },
            { x: 12, y: 16, w: 6, h: 3, i: "h", show: false },
            { x: 16, y: 6, w: 4, h: 5, i: "i", show: false },
          ],
        },
        {
          number: "2",
          name: "protalB",
          layout: [
            {
              x: 0,
              y: 0,
              h: 10,
              w: 16,
              i: 0,
              show: false,
              name: "轮播图",
              component: "slider",
            },
            {
              x: 16,
              y: 0,
              h: 10,
              w: 8,
              i: 2,
              show: false,
              name: "日历",
              component: "calendar",
            },
            {
              x: 0,
              y: 10,
              h: 4,
              w: 16,
              i: 3,
              show: false,
              name: "任务中心",
              component: "task",
            },
            {
              x: 16,
              y: 10,
              h: 7,
              w: 8,
              i: 4,
              show: false,
              name: "常用链接",
              component: "links",
            },
          ],
        },
        {
          number: "3",
          name: "protalC",
          layout: [
            {
              x: 0,
              y: 0,
              w: 24,
              h: 3,
              i: 0,
              component: "shortcuts",
              name: "快捷方式",
              show: false,
              moved: false,
            },
            {
              x: 0,
              y: 2,
              w: 17,
              h: 9,
              i: 2,
              component: "slider",
              name: "轮播图",
              show: false,
              moved: false,
            },
            {
              x: 17,
              y: 2,
              w: 7,
              h: 12,
              i: 3,
              component: "calendar",
              name: "日历",
              show: false,
              moved: false,
            },
            {
              x: 0,
              y: 18,
              w: 8,
              h: 7,
              i: 4,
              component: "links",
              name: "新闻中心",
              show: false,
              moved: false,
            },
            {
              x: 8,
              y: 18,
              w: 8,
              h: 7,
              i: 5,
              component: "links",
              name: "教育",
              show: false,
              moved: false,
            },
            {
              x: 16,
              y: 18,
              w: 8,
              h: 7,
              i: 6,
              component: "links",
              name: "财务",
              show: false,
              moved: false,
            },
            {
              x: 0,
              y: 11,
              w: 17,
              h: 7,
              i: 7,
              component: "task",
              name: "我的任务",
              show: false,
              moved: false,
            },
            {
              x: 17,
              y: 14,
              w: 7,
              h: 4,
              i: 8,
              component: "links",
              name: "常用资料",
              show: false,
              moved: false,
            },
          ],
        },
        {
          number: "4",
          name: "左侧导航",
          layout: [
            {
              x: 0,
              y: 0,
              h: 4,
              w: 4,
              i: 0,
              show: false,
              name: "常用链接",
              component: "links",
            },
          ],
        },
      ],
    },
    //组件
    tools: {
      tools: [
        {
          component: "test1",
          name: "轮播图",
        },
        {
          component: "test2",
          name: "导航链接",
        },
        {
          component: "test3",
          name: "常用资料",
        },
        {
          component: "news",
          name: "新闻中心",
        },
        {
          component: "task",
          name: "我的任务",
        },
        {
          component: "links",
          name: "常用链接",
        },
        {
          component: "shortcuts",
          name: "快捷方式",
        },
      ],
    },
    //主题
    theme: {
      theme: [
        {
          number: 1,
          id: "nomorl theme",
          name: "普通主题",
        },
        {
          number: 2,
          id: "blue theme",
          name: "偏蓝主题",
        },
        {
          number: 3,
          id: "light theme",
          name: "明亮主题",
        },
        {
          number: 1,
          id: "drak theme",
          name: "暗系主题",
        },
      ],
    },
    //配色方案
    themes: {
      themes: [
        {
          cName: "清新",
          name: "cleanTheme",
          mainColor: "#55cfde",
          secMainColor: "white",
          backgColor: "#eeeeee",
          fontColor: "#9FACBB",
        },
        {
          cName: "常规",
          name: "normalTheme",
          mainColor: "#2B2D42",
          secMainColor: "#EE1B35",
          backgColor: "#2B2D42",
          fontColor: "#9FACBB",
        },
        {
          cName: "常规二",
          name: "normalToTheme",
          mainColor: "#171A2B",
          secMainColor: "#EE1B35",
          backgColor: "#EAEAEA",
          fontColor: "#9FACBB",
        },
        {
          cName: "粗糙",
          name: "roughTheme",
          mainColor: "#2E3235",
          secMainColor: "#B5B5B5",
          backgColor: "#F4F4F4",
          fontColor: "#FC6463",
        },
        {
          cName: "简约",
          name: "simpleTheme",
          mainColor: "white",
          secMainColor: "white",
          backgColor: "#F7F7F7",
          fontColor: "#0C79F8",
        },
        {
          cName: "骚",
          name: "sexyTheme",
          mainColor: "white",
          secMainColor: "white",
          backgColor: "#FAFAFA",
          fontColor: "#C760A7",
        },
      ],
    },
    //图标库
    icons: {
      icons: [
        {
          icon_id: "6570217",
          name: "招待",
          font_class: "zhaodai",
          unicode: "e619",
          unicode_decimal: 58905,
        },
        {
          icon_id: "6570218",
          name: "差旅",
          font_class: "-",
          unicode: "e61a",
          unicode_decimal: 58906,
        },
        {
          icon_id: "6570219",
          name: "钱包",
          font_class: "qianbao",
          unicode: "e61b",
          unicode_decimal: 58907,
        },
        {
          icon_id: "6570220",
          name: "扫码",
          font_class: "saoma",
          unicode: "e61c",
          unicode_decimal: 58908,
        },
        {
          icon_id: "6570221",
          name: "建筑",
          font_class: "jianzhu",
          unicode: "e61d",
          unicode_decimal: 58909,
        },
        {
          icon_id: "6570222",
          name: "用车",
          font_class: "yongche",
          unicode: "e61e",
          unicode_decimal: 58910,
        },
        {
          icon_id: "6570223",
          name: "待办",
          font_class: "daiban",
          unicode: "e61f",
          unicode_decimal: 58911,
        },
        {
          icon_id: "6570224",
          name: "目录",
          font_class: "mulu",
          unicode: "e620",
          unicode_decimal: 58912,
        },
        {
          icon_id: "6570225",
          name: "手机",
          font_class: "shouji",
          unicode: "e621",
          unicode_decimal: 58913,
        },
        {
          icon_id: "6570226",
          name: "发票",
          font_class: "fapiao",
          unicode: "e622",
          unicode_decimal: 58914,
        },
        {
          icon_id: "6570227",
          name: "申请",
          font_class: "shenqing",
          unicode: "e623",
          unicode_decimal: 58915,
        },
        {
          icon_id: "6570228",
          name: "知识",
          font_class: "zhishi",
          unicode: "e624",
          unicode_decimal: 58916,
        },
        {
          icon_id: "6570229",
          name: "文件夹",
          font_class: "wenjianjia",
          unicode: "e625",
          unicode_decimal: 58917,
        },
        {
          icon_id: "6570230",
          name: "文档",
          font_class: "wendang",
          unicode: "e626",
          unicode_decimal: 58918,
        },
        {
          icon_id: "6570231",
          name: "新闻",
          font_class: "xinwen",
          unicode: "e627",
          unicode_decimal: 58919,
        },
        {
          icon_id: "6570232",
          name: "填写",
          font_class: "tianxie",
          unicode: "e628",
          unicode_decimal: 58920,
        },
        {
          icon_id: "6570233",
          name: "日程",
          font_class: "richeng",
          unicode: "e629",
          unicode_decimal: 58921,
        },
        {
          icon_id: "6570234",
          name: "文件",
          font_class: "wenjian",
          unicode: "e62a",
          unicode_decimal: 58922,
        },
        {
          icon_id: "6570235",
          name: "首页",
          font_class: "shouye",
          unicode: "e62b",
          unicode_decimal: 58923,
        },
        {
          icon_id: "6570236",
          name: "消息",
          font_class: "xiaoxi",
          unicode: "e62c",
          unicode_decimal: 58924,
        },
      ],
    },
    //门户清单
    // 页面清单
  },
  mutations: {},
  actions: {},
  modules: {},
});
